using ClosedXML.Excel;
using HelpDesk.Api.Application.Reports;
using HelpDesk.Api.Contracts.Reports;
using HelpDesk.Api.Application.Tickets;
using PdfSharp.Drawing;
using PdfSharp.Pdf;

namespace HelpDesk.Api.Infrastructure.Reports;

public sealed class ReportExportService(IReportService reports,TimeProvider timeProvider):IReportExportService
{
    public const string PdfContentType="application/pdf";
    public const string ExcelContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";

    public async Task<ReportExportResult> ExportTicketReportPdfAsync(TicketReportRequest request,TicketAccessContext accessContext,CancellationToken cancellationToken=default)
    {var data=await reports.GetTicketReportAsync(request,accessContext,cancellationToken);cancellationToken.ThrowIfCancellationRequested();var generated=timeProvider.GetUtcNow().UtcDateTime;using var document=new PdfDocument();document.Info.Title="IT Help Desk - Ticket Report";document.Options.CompressContentStreams=false;var writer=new PdfWriter(document);writer.Title("IT Help Desk - Ticket Report");writer.Text($"Generated: {generated:yyyy-MM-dd HH:mm:ss} UTC");writer.Section("Applied filters");foreach(var line in Filters(request,data))writer.Text(line);writer.Section("Summary");writer.Table(["Metric","Count"],Summary(data));writer.Section("Status breakdown");writer.Table(["Status","Tickets"],Rows(data.StatusBreakdown));writer.Section("Priority breakdown");writer.Table(["Priority","Tickets"],Rows(data.PriorityBreakdown));writer.Section("Category breakdown");writer.Table(["Category","Tickets"],Rows(data.CategoryBreakdown));writer.Section("Ticket trend");writer.Table(["Date (UTC)","Created","Closed"],data.Trend.Select(x=>new[]{x.PeriodStartUtc.ToString("yyyy-MM-dd"),x.CreatedCount.ToString(),x.ClosedCount.ToString()}));writer.Section("Agent workload");writer.Table(["Support agent","Active tickets"],data.AgentWorkload.Select(x=>new[]{x.DisplayName,x.ActiveTicketCount.ToString()}));writer.Finish();using var stream=new MemoryStream();document.Save(stream,false);return new(stream.ToArray(),PdfContentType,FileName(generated,"pdf"));}

    public async Task<ReportExportResult> ExportTicketReportExcelAsync(TicketReportRequest request,TicketAccessContext accessContext,CancellationToken cancellationToken=default)
    {var data=await reports.GetTicketReportAsync(request,accessContext,cancellationToken);cancellationToken.ThrowIfCancellationRequested();var generated=timeProvider.GetUtcNow().UtcDateTime;using var workbook=new XLWorkbook();var summary=workbook.AddWorksheet("Summary");summary.Cell("A1").Value="IT Help Desk - Ticket Report";summary.Cell("A2").Value=$"Generated: {generated:yyyy-MM-dd HH:mm:ss} UTC";summary.Cell("A4").Value="Applied filters";var row=5;foreach(var line in Filters(request,data))summary.Cell(row++,1).Value=line;row++;WriteTable(summary,row,["Metric","Count"],Summary(data));WriteTable(workbook.AddWorksheet("Status"),1,["Status","Tickets"],Rows(data.StatusBreakdown));WriteTable(workbook.AddWorksheet("Priority"),1,["Priority","Tickets"],Rows(data.PriorityBreakdown));WriteTable(workbook.AddWorksheet("Categories"),1,["Category","Tickets"],Rows(data.CategoryBreakdown));WriteTable(workbook.AddWorksheet("Trend"),1,["Date (UTC)","Created","Closed"],data.Trend.Select(x=>new object[]{x.PeriodStartUtc.Date,x.CreatedCount,x.ClosedCount}));WriteTable(workbook.AddWorksheet("Agent Workload"),1,["Support agent","Active tickets"],data.AgentWorkload.Select(x=>new object[]{x.DisplayName,x.ActiveTicketCount}));foreach(var sheet in workbook.Worksheets){sheet.Columns().AdjustToContents(1,60);sheet.SheetView.FreezeRows(sheet==summary?0:1);}summary.Cell("A1").Style.Font.SetBold().Font.SetFontSize(16);summary.Cell("A4").Style.Font.SetBold();using var stream=new MemoryStream();workbook.SaveAs(stream);return new(stream.ToArray(),ExcelContentType,FileName(generated,"xlsx"));}

    private static IEnumerable<string>Filters(TicketReportRequest request,TicketReportResponse data){yield return $"Date range: {(request.FromUtc.HasValue?request.FromUtc.Value.ToString("yyyy-MM-dd")+" UTC":"All dates")} to {(request.ToUtc.HasValue?request.ToUtc.Value.ToString("yyyy-MM-dd")+" UTC":"All dates")}";yield return $"Category: {Name(request.CategoryId,data.CategoryBreakdown)}";yield return $"Priority: {Name(request.PriorityId,data.PriorityBreakdown)}";yield return $"Status: {Name(request.StatusId,data.StatusBreakdown)}";yield return $"Assigned agent: {(request.AssignedToUserId.HasValue?data.AgentWorkload.FirstOrDefault(x=>x.UserId==request.AssignedToUserId)?.DisplayName??"Selected agent":"All agents")}";}
    private static string Name(short?id,IReadOnlyList<TicketReportBreakdownResponse> items)=>id.HasValue?items.FirstOrDefault(x=>x.Id==id)?.Name??"Selected value":"All";
    private static IEnumerable<object[]>Summary(TicketReportResponse x)=>new[]{new object[]{"Total Tickets",x.Summary.TotalTickets},["Open / Non-Terminal",x.Summary.OpenTickets],["Terminal / Closed",x.Summary.TerminalTickets],["Cancelled",x.Summary.CancelledTickets],["Assigned",x.Summary.AssignedTickets],["Unassigned",x.Summary.UnassignedTickets],["Average Resolution Time",FormatDuration(x.Summary.AverageResolutionMinutes)]};
    private static string FormatDuration(double? minutes)=>minutes is null?"N/A":minutes.Value<60?$"{minutes.Value:0}m":minutes.Value<1440?$"{Math.Floor(minutes.Value/60):0}h {minutes.Value%60:0}m":$"{Math.Floor(minutes.Value/1440):0}d {minutes.Value%1440/60:0}h";
    private static IEnumerable<object[]>Rows(IEnumerable<TicketReportBreakdownResponse> rows)=>rows.Select(x=>new object[]{x.Name,x.Count});
    private static string FileName(DateTime utc,string extension)=>$"ticket-report-{utc:yyyyMMdd-HHmmss}.{extension}";
    private static void WriteTable(IXLWorksheet sheet,int start,IReadOnlyList<string> headers,IEnumerable<object[]> rows){for(var column=0;column<headers.Count;column++)sheet.Cell(start,column+1).Value=headers[column];var header=sheet.Range(start,1,start,headers.Count);header.Style.Font.SetBold().Font.SetFontColor(XLColor.White);header.Style.Fill.SetBackgroundColor(XLColor.FromHtml("#315BD6"));var row=start+1;foreach(var values in rows){for(var column=0;column<values.Length;column++)sheet.Cell(row,column+1).Value=XLCellValue.FromObject(values[column]);row++;}if(row>start+1)sheet.Range(start,1,row-1,headers.Count).Style.Border.OutsideBorder=XLBorderStyleValues.Thin;}
    private sealed class PdfWriter(PdfDocument document)
    {private readonly XFont title=new(ReportPdfFontConfiguration.FamilyName,18,XFontStyleEx.Bold);private readonly XFont heading=new(ReportPdfFontConfiguration.FamilyName,12,XFontStyleEx.Bold);private readonly XFont body=new(ReportPdfFontConfiguration.FamilyName,9);private readonly XFont tableHeading=new(ReportPdfFontConfiguration.FamilyName,9,XFontStyleEx.Bold);private PdfPage page=null!;private XGraphics graphics=null!;private double y;
        public void Title(string value){NewPage();graphics.DrawString(value,title,XBrushes.DarkBlue,new XRect(40,y,page.Width.Point-80,26),XStringFormats.TopLeft);y+=34;}
        public void Section(string value){Ensure(28);y+=8;graphics.DrawString(value,heading,XBrushes.DarkBlue,new XPoint(40,y+12));y+=22;}
        public void Text(string value){Ensure(16);graphics.DrawString(Trim(value,105),body,XBrushes.Black,new XPoint(40,y+10));y+=14;}
        public void Table(string[] headers,IEnumerable<object[]> rows){var values=rows.Select(x=>x.Select(v=>v?.ToString()??string.Empty).ToArray()).ToArray();DrawRow(headers,true);foreach(var row in values)DrawRow(row,false);}
        private void DrawRow(string[] cells,bool header){Ensure(20);var width=(page.Width.Point-80)/cells.Length;for(var i=0;i<cells.Length;i++){var rect=new XRect(40+i*width,y,width,18);graphics.DrawRectangle(XPens.LightGray,header?new XSolidBrush(XColor.FromArgb(49,91,214)):XBrushes.White,rect);graphics.DrawString(Trim(cells[i],Math.Max(12,(int)(width/5.3))),header?tableHeading:body,header?XBrushes.White:XBrushes.Black,new XRect(rect.X+4,rect.Y+3,rect.Width-8,rect.Height-4),XStringFormats.TopLeft);}y+=18;}
        private void Ensure(double height){if(y+height>page.Height.Point-45)NewPage();}
        private void NewPage(){graphics?.Dispose();page=document.AddPage();page.Size=PdfSharp.PageSize.A4;graphics=XGraphics.FromPdfPage(page);y=38;}
        public void Finish(){graphics.Dispose();for(var index=0;index<document.PageCount;index++){using var g=XGraphics.FromPdfPage(document.Pages[index],XGraphicsPdfPageOptions.Append);g.DrawString($"Page {index+1} of {document.PageCount}",body,XBrushes.Gray,new XRect(40,document.Pages[index].Height.Point-30,document.Pages[index].Width.Point-80,15),XStringFormats.TopRight);}}
        private static string Trim(string value,int max)=>value.Length<=max?value:value[..Math.Max(1,max-1)]+"…";}
}
