import {render,screen} from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import {MemoryRouter} from 'react-router-dom'
import {beforeEach,describe,expect,it,vi} from 'vitest'
import {NotificationsPage} from './NotificationsPage'
const actions={reload:vi.fn(),markAsRead:vi.fn(),markAllAsRead:vi.fn(),setUnreadOnly:vi.fn(),setPageNumber:vi.fn()};let state:Record<string,unknown>
vi.mock('../auth/useNotifications',()=>({useNotifications:()=>state}))
const unread={id:'n1',ticketId:'ticket-1',type:'TicketAssigned',title:'Assigned',message:'<img src=x onerror=alert(1)> plain message',createdAtUtc:'2026-08-06T12:00:00Z',readAtUtc:null,isRead:false};const read={...unread,id:'n2',ticketId:null,title:'Status changed',message:'Done',readAtUtc:'2026-08-06T12:01:00Z',isRead:true};
const renderPage=()=>render(<MemoryRouter><NotificationsPage/></MemoryRouter>);describe('NotificationsPage',()=>{beforeEach(()=>{Object.values(actions).forEach(x=>x.mockReset());actions.markAsRead.mockResolvedValue(undefined);actions.markAllAsRead.mockResolvedValue(undefined);state={...actions,notifications:[unread,read],unreadCount:1,pageNumber:1,totalPages:2,hasPreviousPage:false,hasNextPage:true,unreadOnly:false,isLoading:false,error:undefined}})
 it('renders accessible loading, empty, and error retry states',async()=>{state={...state,isLoading:true};const view=renderPage();expect(screen.getByRole('status')).toHaveTextContent('Loading notifications');view.unmount();state={...state,isLoading:false,notifications:[]};const emptyView=renderPage();expect(screen.getByText('No notifications to show')).toBeInTheDocument();emptyView.unmount();state={...state,error:new Error('offline')};renderPage();expect(screen.getByRole('alert')).toHaveTextContent('could not be loaded');await userEvent.click(screen.getByRole('button',{name:'Retry'}));expect(actions.reload).toHaveBeenCalledOnce()})
 it('renders read and unread items, safe date, ticket link, and no broken link',()=>{renderPage();expect(screen.getByText('Unread')).toBeInTheDocument();expect(document.querySelector('.notification.unread')).not.toBeNull();expect(document.querySelector('.notification.read')).not.toBeNull();expect(screen.getByRole('link',{name:'View ticket'})).toHaveAttribute('href','/app/tickets/ticket-1');expect(screen.getAllByRole('link',{name:'View ticket'})).toHaveLength(1);expect(screen.getAllByRole('time')[0]).toHaveAttribute('datetime',unread.createdAtUtc)})
 it('renders message as plain text without HTML execution or unsafe fields',()=>{renderPage();expect(screen.getByText(unread.message)).toBeInTheDocument();expect(document.querySelector('img')).toBeNull();expect(document.body).not.toHaveTextContent(/recipientUserId|email@example|accessToken/i)})
 it('marks individual and all notifications with keyboard-accessible buttons',async()=>{renderPage();await userEvent.click(screen.getByRole('button',{name:'Mark as read'}));expect(actions.markAsRead).toHaveBeenCalledWith('n1');await userEvent.click(screen.getByRole('button',{name:'Mark all as read'}));expect(actions.markAllAsRead).toHaveBeenCalledOnce()})
 it('changes unread filter and navigates pages',async()=>{renderPage();await userEvent.click(screen.getByRole('checkbox',{name:'Unread only'}));expect(actions.setUnreadOnly).toHaveBeenCalledWith(true);expect(screen.getByRole('button',{name:'Previous'})).toBeDisabled();await userEvent.click(screen.getByRole('button',{name:'Next'}));expect(actions.setPageNumber).toHaveBeenCalledWith(2)})
 it('disables mark-all consistently at zero unread',()=>{state={...state,unreadCount:0};renderPage();expect(screen.getByRole('button',{name:'Mark all as read'})).toBeDisabled()})
})
