import {render,screen,waitFor} from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import {MemoryRouter} from 'react-router-dom'
import {beforeEach,describe,expect,it,vi} from 'vitest'
import * as authApi from '../api/authApi'
import {ForgotPasswordPage} from './ForgotPasswordPage'
import {ResetPasswordPage} from './ResetPasswordPage'

vi.mock('../api/authApi',()=>({forgotPasswordAsync:vi.fn(),resetPasswordAsync:vi.fn()}))
describe('password reset pages',()=>{beforeEach(()=>{vi.mocked(authApi.forgotPasswordAsync).mockReset();vi.mocked(authApi.resetPasswordAsync).mockReset()});it('renders and always shows the generic forgot-password success',async()=>{vi.mocked(authApi.forgotPasswordAsync).mockResolvedValue({message:'ignored'});render(<MemoryRouter><ForgotPasswordPage/></MemoryRouter>);await userEvent.type(screen.getByLabelText('Email'),'user@example.test');await userEvent.click(screen.getByRole('button',{name:'Send reset instructions'}));expect(await screen.findByText(/If an account exists/)).toBeInTheDocument();expect(authApi.forgotPasswordAsync).toHaveBeenCalledWith({email:'user@example.test'})});it('validates reset password confirmation',async()=>{render(<MemoryRouter initialEntries={['/reset-password?email=user%40example.test&token=abc']}><ResetPasswordPage/></MemoryRouter>);await userEvent.type(screen.getByLabelText('New password'),'Password2!');await userEvent.type(screen.getByLabelText('Confirm password'),'Different2!');await userEvent.click(screen.getByRole('button',{name:'Reset password'}));expect(screen.getByText('Passwords do not match.')).toBeInTheDocument()});it('submits token and displays success',async()=>{vi.mocked(authApi.resetPasswordAsync).mockResolvedValue({message:'ok'});render(<MemoryRouter initialEntries={['/reset-password?email=user%40example.test&token=abc']}><ResetPasswordPage/></MemoryRouter>);await userEvent.type(screen.getByLabelText('New password'),'Password2!');await userEvent.type(screen.getByLabelText('Confirm password'),'Password2!');await userEvent.click(screen.getByRole('button',{name:'Reset password'}));await waitFor(()=>expect(authApi.resetPasswordAsync).toHaveBeenCalledWith({email:'user@example.test',token:'abc',newPassword:'Password2!',confirmPassword:'Password2!'}));expect(await screen.findByText('Your password has been reset.')).toBeInTheDocument()})})
