import {useEffect,useState} from 'react'
import {NavLink,Outlet,useNavigate} from 'react-router-dom'
import {BarChart3,Bell,ChevronRight,ClipboardList,LayoutDashboard,LogOut,Menu,PlusCircle,ScrollText,ShieldCheck,UserCog,UsersRound,UserRound,X} from 'lucide-react'
import {useAuth} from '../auth/AuthProvider'
import {AppRoles,RoleGroups} from '../auth/roles'
import {NotificationsProvider,useNotifications} from '../auth/useNotifications'

export function AppLayout(){return <NotificationsProvider><AuthenticatedLayout/></NotificationsProvider>}

function AuthenticatedLayout(){
  const auth=useAuth();const navigate=useNavigate();const[busy,setBusy]=useState(false);const[open,setOpen]=useState(false);const notifications=useNotifications()
  useEffect(()=>{if(!open)return;const close=(event:KeyboardEvent)=>{if(event.key==='Escape')setOpen(false)};document.addEventListener('keydown',close);return()=>document.removeEventListener('keydown',close)},[open])
  async function logout(){if(busy)return;setBusy(true);try{await auth.logout()}finally{navigate('/login',{replace:true})}}
  const links=[{to:'/app/home',label:'Dashboard',icon:LayoutDashboard},{to:'/app/tickets',label:'Tickets',icon:ClipboardList},{to:'/app/tickets/new',label:'Create Ticket',icon:PlusCircle},{to:'/app/notifications',label:'Notifications',icon:Bell},{to:'/app/profile',label:'Profile',icon:UserRound},...(RoleGroups.Reports.some(role=>auth.roles.includes(role))?[{to:'/app/reports',label:'Reports',icon:BarChart3}]:[]),...(RoleGroups.SupportStaff.some(role=>auth.roles.includes(role))?[{to:'/app/activity',label:'Activity Log',icon:ScrollText}]:[]),...(auth.roles.includes(AppRoles.Admin)?[{to:'/app/team-management',label:'Team Management',icon:UsersRound},{to:'/app/role-management',label:'Role Management',icon:UserCog}]:[])]
  return <div className="app-shell">{open&&<button className="nav-scrim" aria-label="Close navigation" onClick={()=>setOpen(false)}/>}<aside className={open?'sidebar is-open':'sidebar'} aria-label="Application sidebar"><div className="brand"><span className="brand-mark"><ShieldCheck/></span><span><strong>IT Help Desk</strong><small>Support workspace</small></span><button className="icon-button sidebar-close" aria-label="Close navigation" onClick={()=>setOpen(false)}><X/></button></div><nav aria-label="Primary navigation">{links.map(({to,label,icon:Icon})=><NavLink key={to} to={to} end={to==='/app/home'} onClick={()=>setOpen(false)}><Icon aria-hidden="true"/><span>{label}</span>{label==='Notifications'&&notifications.unreadCount>0&&<span className="notification-badge" aria-label={`${notifications.unreadCount} unread notifications`}>{notifications.unreadCount>99?'99+':notifications.unreadCount}</span>}<ChevronRight className="nav-chevron" aria-hidden="true"/></NavLink>)}</nav><div className="sidebar-account"><div className="avatar" aria-hidden="true">{auth.user?.displayName?.charAt(0).toUpperCase()}</div><div><strong>{auth.user?.displayName}</strong><small>{auth.roles.join(', ')}</small></div><button className="icon-button" onClick={logout} disabled={busy} aria-label={busy?'Signing out':'Sign out'}><LogOut/></button></div></aside><div className="app-stage"><header className="topbar"><button className="icon-button menu-button" aria-label="Open navigation" aria-expanded={open} onClick={()=>setOpen(true)}><Menu/></button><div><span className="eyebrow">Support workspace</span><strong>Manage requests with clarity</strong></div><div className="topbar-actions"><NavLink className="icon-button notification-button" to="/app/notifications" aria-label={notifications.unreadCount?`${notifications.unreadCount} unread notifications`:'Notifications'}><Bell/>{notifications.unreadCount>0&&<span>{notifications.unreadCount>99?'99+':notifications.unreadCount}</span>}</NavLink><NavLink className="button-link compact" to="/app/tickets/new"><PlusCircle/>New ticket</NavLink></div></header><main id="main-content"><Outlet/></main></div></div>
}
