CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE EXTENSION IF NOT EXISTS citext;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE TABLE "Categories" (
        "Id" smallint GENERATED BY DEFAULT AS IDENTITY,
        "Name" citext NOT NULL,
        "Description" character varying(500),
        "SortOrder" smallint NOT NULL DEFAULT 0,
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "CreatedAtUtc" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Categories" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE TABLE "Priorities" (
        "Id" smallint GENERATED BY DEFAULT AS IDENTITY,
        "Name" citext NOT NULL,
        "Rank" smallint NOT NULL,
        "Description" character varying(500),
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "CreatedAtUtc" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Priorities" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_Priorities_Rank_Positive" CHECK ("Rank" > 0)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE TABLE "Roles" (
        "Id" uuid NOT NULL,
        "Description" character varying(500),
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "CreatedAtUtc" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        "Name" character varying(100) NOT NULL,
        "NormalizedName" character varying(100) NOT NULL,
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE TABLE "Statuses" (
        "Id" smallint GENERATED BY DEFAULT AS IDENTITY,
        "Name" citext NOT NULL,
        "Description" character varying(500),
        "SortOrder" smallint NOT NULL DEFAULT 0,
        "IsTerminal" boolean NOT NULL DEFAULT FALSE,
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "CreatedAtUtc" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Statuses" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE TABLE "Users" (
        "Id" uuid NOT NULL,
        "DisplayName" character varying(200) NOT NULL,
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "CreatedAtUtc" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        "DeactivatedAtUtc" timestamp with time zone,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(320) NOT NULL,
        "NormalizedEmail" character varying(320) NOT NULL,
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_Users_DeactivatedWhenInactive" CHECK ("IsActive" = FALSE OR "DeactivatedAtUtc" IS NULL),
        CONSTRAINT "CK_Users_DisplayName_NotBlank" CHECK (btrim("DisplayName") <> '')
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE TABLE "RoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" uuid NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_RoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_RoleClaims_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE TABLE "ActivityLogs" (
        "Id" bigint GENERATED ALWAYS AS IDENTITY,
        "ActorUserId" uuid,
        "Action" character varying(150) NOT NULL,
        "EntityType" character varying(100) NOT NULL,
        "EntityIdentifier" character varying(100) NOT NULL,
        "OccurredAtUtc" timestamp with time zone NOT NULL,
        "Metadata" jsonb,
        CONSTRAINT "PK_ActivityLogs" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ActivityLogs_Users_ActorUserId" FOREIGN KEY ("ActorUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE TABLE "Tickets" (
        "Id" uuid NOT NULL,
        "ReferenceNumber" character varying(30) NOT NULL,
        "Title" character varying(250) NOT NULL,
        "Description" text NOT NULL,
        "CategoryId" smallint NOT NULL,
        "PriorityId" smallint NOT NULL,
        "StatusId" smallint NOT NULL,
        "CreatedByUserId" uuid NOT NULL,
        "AssignedToUserId" uuid,
        "CreatedAtUtc" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAtUtc" timestamp with time zone NOT NULL,
        "ResolvedAtUtc" timestamp with time zone,
        "ClosedAtUtc" timestamp with time zone,
        "CancelledAtUtc" timestamp with time zone,
        CONSTRAINT "PK_Tickets" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_Tickets_Description_NotBlank" CHECK (btrim("Description") <> ''),
        CONSTRAINT "CK_Tickets_ReferenceNumber_NotBlank" CHECK (btrim("ReferenceNumber") <> ''),
        CONSTRAINT "CK_Tickets_Title_NotBlank" CHECK (btrim("Title") <> ''),
        CONSTRAINT "FK_Tickets_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Tickets_Priorities_PriorityId" FOREIGN KEY ("PriorityId") REFERENCES "Priorities" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Tickets_Statuses_StatusId" FOREIGN KEY ("StatusId") REFERENCES "Statuses" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Tickets_Users_AssignedToUserId" FOREIGN KEY ("AssignedToUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Tickets_Users_CreatedByUserId" FOREIGN KEY ("CreatedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE TABLE "UserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" uuid NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_UserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_UserClaims_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE TABLE "UserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" uuid NOT NULL,
        CONSTRAINT "PK_UserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_UserLogins_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE TABLE "UserRoles" (
        "UserId" uuid NOT NULL,
        "RoleId" uuid NOT NULL,
        "AssignedAtUtc" timestamp with time zone NOT NULL,
        "AssignedByUserId" uuid,
        CONSTRAINT "PK_UserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_UserRoles_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_UserRoles_Users_AssignedByUserId" FOREIGN KEY ("AssignedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_UserRoles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE TABLE "UserTokens" (
        "UserId" uuid NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_UserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_UserTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE TABLE "Notifications" (
        "Id" uuid NOT NULL,
        "RecipientUserId" uuid NOT NULL,
        "TicketId" uuid,
        "Type" character varying(100) NOT NULL,
        "Title" character varying(250) NOT NULL,
        "Message" text NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "ReadAtUtc" timestamp with time zone,
        "ExpiresAtUtc" timestamp with time zone,
        CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Notifications_Tickets_TicketId" FOREIGN KEY ("TicketId") REFERENCES "Tickets" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Notifications_Users_RecipientUserId" FOREIGN KEY ("RecipientUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE TABLE "TicketAssignments" (
        "Id" uuid NOT NULL,
        "TicketId" uuid NOT NULL,
        "AssignedToUserId" uuid NOT NULL,
        "AssignedByUserId" uuid,
        "AssignedAtUtc" timestamp with time zone NOT NULL,
        "EndedAtUtc" timestamp with time zone,
        "EndedByUserId" uuid,
        "Reason" character varying(500),
        CONSTRAINT "PK_TicketAssignments" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_TicketAssignments_EndedAfterAssigned" CHECK ("EndedAtUtc" IS NULL OR "EndedAtUtc" >= "AssignedAtUtc"),
        CONSTRAINT "FK_TicketAssignments_Tickets_TicketId" FOREIGN KEY ("TicketId") REFERENCES "Tickets" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_TicketAssignments_Users_AssignedByUserId" FOREIGN KEY ("AssignedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_TicketAssignments_Users_AssignedToUserId" FOREIGN KEY ("AssignedToUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_TicketAssignments_Users_EndedByUserId" FOREIGN KEY ("EndedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE TABLE "TicketComments" (
        "Id" uuid NOT NULL,
        "TicketId" uuid NOT NULL,
        "AuthorUserId" uuid NOT NULL,
        "Body" text NOT NULL,
        "Visibility" character varying(20) NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "UpdatedAtUtc" timestamp with time zone,
        "DeletedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_TicketComments" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_TicketComments_Body_NotBlank" CHECK (btrim("Body") <> ''),
        CONSTRAINT "CK_TicketComments_Visibility" CHECK ("Visibility" IN ('Public', 'Internal')),
        CONSTRAINT "FK_TicketComments_Tickets_TicketId" FOREIGN KEY ("TicketId") REFERENCES "Tickets" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_TicketComments_Users_AuthorUserId" FOREIGN KEY ("AuthorUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE TABLE "TicketStatusHistory" (
        "Id" uuid NOT NULL,
        "TicketId" uuid NOT NULL,
        "FromStatusId" smallint,
        "ToStatusId" smallint NOT NULL,
        "ChangedByUserId" uuid,
        "ChangedAtUtc" timestamp with time zone NOT NULL,
        "Reason" character varying(1000),
        CONSTRAINT "PK_TicketStatusHistory" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_TicketStatusHistory_StatusChanged" CHECK ("FromStatusId" IS NULL OR "FromStatusId" <> "ToStatusId"),
        CONSTRAINT "FK_TicketStatusHistory_Statuses_FromStatusId" FOREIGN KEY ("FromStatusId") REFERENCES "Statuses" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_TicketStatusHistory_Statuses_ToStatusId" FOREIGN KEY ("ToStatusId") REFERENCES "Statuses" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_TicketStatusHistory_Tickets_TicketId" FOREIGN KEY ("TicketId") REFERENCES "Tickets" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_TicketStatusHistory_Users_ChangedByUserId" FOREIGN KEY ("ChangedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE TABLE "TicketAttachments" (
        "Id" uuid NOT NULL,
        "TicketId" uuid NOT NULL,
        "CommentId" uuid,
        "UploadedByUserId" uuid NOT NULL,
        "OriginalFileName" character varying(255) NOT NULL,
        "ContentType" character varying(150) NOT NULL,
        "SizeBytes" bigint NOT NULL,
        "StorageProvider" character varying(50) NOT NULL,
        "StorageKey" character varying(1024) NOT NULL,
        "ContentHash" character varying(128),
        "CreatedAtUtc" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
        "DeletedAtUtc" timestamp with time zone,
        CONSTRAINT "PK_TicketAttachments" PRIMARY KEY ("Id"),
        CONSTRAINT "CK_TicketAttachments_SizeBytes_NonNegative" CHECK ("SizeBytes" >= 0),
        CONSTRAINT "FK_TicketAttachments_TicketComments_CommentId" FOREIGN KEY ("CommentId") REFERENCES "TicketComments" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_TicketAttachments_Tickets_TicketId" FOREIGN KEY ("TicketId") REFERENCES "Tickets" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_TicketAttachments_Users_UploadedByUserId" FOREIGN KEY ("UploadedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    INSERT INTO "Categories" ("Id", "CreatedAtUtc", "Description", "IsActive", "Name", "SortOrder", "UpdatedAtUtc")
    VALUES (1, TIMESTAMPTZ '2026-01-01T00:00:00Z', NULL, TRUE, 'Hardware', 1, TIMESTAMPTZ '2026-01-01T00:00:00Z');
    INSERT INTO "Categories" ("Id", "CreatedAtUtc", "Description", "IsActive", "Name", "SortOrder", "UpdatedAtUtc")
    VALUES (2, TIMESTAMPTZ '2026-01-01T00:00:00Z', NULL, TRUE, 'Software', 2, TIMESTAMPTZ '2026-01-01T00:00:00Z');
    INSERT INTO "Categories" ("Id", "CreatedAtUtc", "Description", "IsActive", "Name", "SortOrder", "UpdatedAtUtc")
    VALUES (3, TIMESTAMPTZ '2026-01-01T00:00:00Z', NULL, TRUE, 'Network', 3, TIMESTAMPTZ '2026-01-01T00:00:00Z');
    INSERT INTO "Categories" ("Id", "CreatedAtUtc", "Description", "IsActive", "Name", "SortOrder", "UpdatedAtUtc")
    VALUES (4, TIMESTAMPTZ '2026-01-01T00:00:00Z', NULL, TRUE, 'Email', 4, TIMESTAMPTZ '2026-01-01T00:00:00Z');
    INSERT INTO "Categories" ("Id", "CreatedAtUtc", "Description", "IsActive", "Name", "SortOrder", "UpdatedAtUtc")
    VALUES (5, TIMESTAMPTZ '2026-01-01T00:00:00Z', NULL, TRUE, 'Access Request', 5, TIMESTAMPTZ '2026-01-01T00:00:00Z');
    INSERT INTO "Categories" ("Id", "CreatedAtUtc", "Description", "IsActive", "Name", "SortOrder", "UpdatedAtUtc")
    VALUES (6, TIMESTAMPTZ '2026-01-01T00:00:00Z', NULL, TRUE, 'Other', 6, TIMESTAMPTZ '2026-01-01T00:00:00Z');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    INSERT INTO "Priorities" ("Id", "CreatedAtUtc", "Description", "IsActive", "Name", "Rank", "UpdatedAtUtc")
    VALUES (1, TIMESTAMPTZ '2026-01-01T00:00:00Z', NULL, TRUE, 'Low', 1, TIMESTAMPTZ '2026-01-01T00:00:00Z');
    INSERT INTO "Priorities" ("Id", "CreatedAtUtc", "Description", "IsActive", "Name", "Rank", "UpdatedAtUtc")
    VALUES (2, TIMESTAMPTZ '2026-01-01T00:00:00Z', NULL, TRUE, 'Medium', 2, TIMESTAMPTZ '2026-01-01T00:00:00Z');
    INSERT INTO "Priorities" ("Id", "CreatedAtUtc", "Description", "IsActive", "Name", "Rank", "UpdatedAtUtc")
    VALUES (3, TIMESTAMPTZ '2026-01-01T00:00:00Z', NULL, TRUE, 'High', 3, TIMESTAMPTZ '2026-01-01T00:00:00Z');
    INSERT INTO "Priorities" ("Id", "CreatedAtUtc", "Description", "IsActive", "Name", "Rank", "UpdatedAtUtc")
    VALUES (4, TIMESTAMPTZ '2026-01-01T00:00:00Z', NULL, TRUE, 'Critical', 4, TIMESTAMPTZ '2026-01-01T00:00:00Z');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    INSERT INTO "Roles" ("Id", "ConcurrencyStamp", "CreatedAtUtc", "Description", "IsActive", "Name", "NormalizedName", "UpdatedAtUtc")
    VALUES ('11111111-1111-1111-1111-111111111111', 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', TIMESTAMPTZ '2026-01-01T00:00:00Z', 'Full administrative access to the help desk system.', TRUE, 'Admin', 'ADMIN', TIMESTAMPTZ '2026-01-01T00:00:00Z');
    INSERT INTO "Roles" ("Id", "ConcurrencyStamp", "CreatedAtUtc", "Description", "IsActive", "Name", "NormalizedName", "UpdatedAtUtc")
    VALUES ('22222222-2222-2222-2222-222222222222', 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', TIMESTAMPTZ '2026-01-01T00:00:00Z', 'Handles and resolves help desk tickets.', TRUE, 'IT Support Agent', 'IT SUPPORT AGENT', TIMESTAMPTZ '2026-01-01T00:00:00Z');
    INSERT INTO "Roles" ("Id", "ConcurrencyStamp", "CreatedAtUtc", "Description", "IsActive", "Name", "NormalizedName", "UpdatedAtUtc")
    VALUES ('33333333-3333-3333-3333-333333333333', 'cccccccc-cccc-cccc-cccc-cccccccccccc', TIMESTAMPTZ '2026-01-01T00:00:00Z', 'Creates and follows help desk requests.', TRUE, 'Employee', 'EMPLOYEE', TIMESTAMPTZ '2026-01-01T00:00:00Z');
    INSERT INTO "Roles" ("Id", "ConcurrencyStamp", "CreatedAtUtc", "Description", "IsActive", "Name", "NormalizedName", "UpdatedAtUtc")
    VALUES ('44444444-4444-4444-4444-444444444444', 'dddddddd-dddd-dddd-dddd-dddddddddddd', TIMESTAMPTZ '2026-01-01T00:00:00Z', 'Oversees team requests and help desk activity.', TRUE, 'Manager', 'MANAGER', TIMESTAMPTZ '2026-01-01T00:00:00Z');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    INSERT INTO "Statuses" ("Id", "CreatedAtUtc", "Description", "IsActive", "Name", "SortOrder", "UpdatedAtUtc")
    VALUES (1, TIMESTAMPTZ '2026-01-01T00:00:00Z', NULL, TRUE, 'Open', 1, TIMESTAMPTZ '2026-01-01T00:00:00Z');
    INSERT INTO "Statuses" ("Id", "CreatedAtUtc", "Description", "IsActive", "Name", "SortOrder", "UpdatedAtUtc")
    VALUES (2, TIMESTAMPTZ '2026-01-01T00:00:00Z', NULL, TRUE, 'In Progress', 2, TIMESTAMPTZ '2026-01-01T00:00:00Z');
    INSERT INTO "Statuses" ("Id", "CreatedAtUtc", "Description", "IsActive", "Name", "SortOrder", "UpdatedAtUtc")
    VALUES (3, TIMESTAMPTZ '2026-01-01T00:00:00Z', NULL, TRUE, 'Pending', 3, TIMESTAMPTZ '2026-01-01T00:00:00Z');
    INSERT INTO "Statuses" ("Id", "CreatedAtUtc", "Description", "IsActive", "Name", "SortOrder", "UpdatedAtUtc")
    VALUES (4, TIMESTAMPTZ '2026-01-01T00:00:00Z', NULL, TRUE, 'Resolved', 4, TIMESTAMPTZ '2026-01-01T00:00:00Z');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    INSERT INTO "Statuses" ("Id", "CreatedAtUtc", "Description", "IsActive", "IsTerminal", "Name", "SortOrder", "UpdatedAtUtc")
    VALUES (5, TIMESTAMPTZ '2026-01-01T00:00:00Z', NULL, TRUE, TRUE, 'Closed', 5, TIMESTAMPTZ '2026-01-01T00:00:00Z');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE INDEX "IX_ActivityLogs_ActorUserId_OccurredAtUtc" ON "ActivityLogs" ("ActorUserId", "OccurredAtUtc") WHERE "ActorUserId" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE INDEX "IX_ActivityLogs_EntityType_EntityIdentifier_OccurredAtUtc" ON "ActivityLogs" ("EntityType", "EntityIdentifier", "OccurredAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE INDEX "IX_ActivityLogs_OccurredAtUtc" ON "ActivityLogs" ("OccurredAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE INDEX "IX_Categories_IsActive_SortOrder" ON "Categories" ("IsActive", "SortOrder");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Categories_Name" ON "Categories" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE INDEX "IX_Notifications_RecipientUserId_CreatedAtUtc" ON "Notifications" ("RecipientUserId", "CreatedAtUtc") WHERE "ReadAtUtc" IS NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE INDEX "IX_Notifications_TicketId" ON "Notifications" ("TicketId") WHERE "TicketId" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE INDEX "IX_Priorities_IsActive" ON "Priorities" ("IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Priorities_Name" ON "Priorities" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Priorities_Rank" ON "Priorities" ("Rank");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE INDEX "IX_RoleClaims_RoleId" ON "RoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE INDEX "IX_Roles_IsActive" ON "Roles" ("IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON "Roles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE INDEX "IX_Statuses_IsActive_SortOrder" ON "Statuses" ("IsActive", "SortOrder");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Statuses_Name" ON "Statuses" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE INDEX "IX_TicketAssignments_AssignedByUserId" ON "TicketAssignments" ("AssignedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE INDEX "IX_TicketAssignments_AssignedToUserId_AssignedAtUtc" ON "TicketAssignments" ("AssignedToUserId", "AssignedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE INDEX "IX_TicketAssignments_EndedByUserId" ON "TicketAssignments" ("EndedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_TicketAssignments_TicketId" ON "TicketAssignments" ("TicketId") WHERE "EndedAtUtc" IS NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE INDEX "IX_TicketAssignments_TicketId_AssignedAtUtc" ON "TicketAssignments" ("TicketId", "AssignedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE INDEX "IX_TicketAttachments_CommentId" ON "TicketAttachments" ("CommentId") WHERE "CommentId" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_TicketAttachments_StorageProvider_StorageKey" ON "TicketAttachments" ("StorageProvider", "StorageKey");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE INDEX "IX_TicketAttachments_TicketId_CreatedAtUtc" ON "TicketAttachments" ("TicketId", "CreatedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE INDEX "IX_TicketAttachments_UploadedByUserId" ON "TicketAttachments" ("UploadedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE INDEX "IX_TicketComments_AuthorUserId" ON "TicketComments" ("AuthorUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE INDEX "IX_TicketComments_TicketId_CreatedAtUtc" ON "TicketComments" ("TicketId", "CreatedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE INDEX "IX_Tickets_AssignedToUserId_StatusId_UpdatedAtUtc" ON "Tickets" ("AssignedToUserId", "StatusId", "UpdatedAtUtc") WHERE "AssignedToUserId" IS NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE INDEX "IX_Tickets_CategoryId_CreatedAtUtc" ON "Tickets" ("CategoryId", "CreatedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE INDEX "IX_Tickets_CreatedByUserId_CreatedAtUtc" ON "Tickets" ("CreatedByUserId", "CreatedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE INDEX "IX_Tickets_PriorityId" ON "Tickets" ("PriorityId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Tickets_ReferenceNumber" ON "Tickets" ("ReferenceNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE INDEX "IX_Tickets_StatusId_PriorityId_CreatedAtUtc" ON "Tickets" ("StatusId", "PriorityId", "CreatedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE INDEX "IX_TicketStatusHistory_ChangedByUserId" ON "TicketStatusHistory" ("ChangedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE INDEX "IX_TicketStatusHistory_FromStatusId" ON "TicketStatusHistory" ("FromStatusId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE INDEX "IX_TicketStatusHistory_TicketId_ChangedAtUtc" ON "TicketStatusHistory" ("TicketId", "ChangedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE INDEX "IX_TicketStatusHistory_ToStatusId_ChangedAtUtc" ON "TicketStatusHistory" ("ToStatusId", "ChangedAtUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE INDEX "IX_UserClaims_UserId" ON "UserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE INDEX "IX_UserLogins_UserId" ON "UserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE INDEX "IX_UserRoles_AssignedByUserId" ON "UserRoles" ("AssignedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE INDEX "IX_UserRoles_RoleId" ON "UserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE UNIQUE INDEX "EmailIndex" ON "Users" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE INDEX "IX_Users_IsActive" ON "Users" ("IsActive") WHERE "IsActive" = TRUE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON "Users" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    PERFORM setval(
        pg_get_serial_sequence('"Categories"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "Categories") + 1,
            nextval(pg_get_serial_sequence('"Categories"', 'Id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('"Priorities"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "Priorities") + 1,
            nextval(pg_get_serial_sequence('"Priorities"', 'Id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('"Statuses"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "Statuses") + 1,
            nextval(pg_get_serial_sequence('"Statuses"', 'Id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260718133039_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260718133039_InitialCreate', '10.0.5');
    END IF;
END $EF$;
COMMIT;

