import {act,renderHook,waitFor} from '@testing-library/react'
import {beforeEach,describe,expect,it,vi} from 'vitest'
import {NotificationsProvider,useNotifications} from './useNotifications'
import type {NotificationPage,NotificationResponse} from '../types/notifications'
const api=vi.hoisted(()=>({list:vi.fn(),count:vi.fn(),read:vi.fn(),all:vi.fn()}))
vi.mock('../api/notifications',()=>({getNotificationsAsync:api.list,getUnreadNotificationCountAsync:api.count,markNotificationReadAsync:api.read,markAllNotificationsReadAsync:api.all}))
const item:NotificationResponse={id:'n1',ticketId:'t1',type:'TicketAssigned',title:'Assigned',message:'Message',createdAtUtc:'2026-08-06T12:00:00Z',readAtUtc:null,isRead:false}
const page=(items=[item]):NotificationPage=>({items,pageNumber:1,pageSize:20,totalCount:items.length,totalPages:items.length?1:0,hasPreviousPage:false,hasNextPage:false})
const wrapper=({children}:{children:React.ReactNode})=><NotificationsProvider>{children}</NotificationsProvider>
describe('useNotifications',()=>{beforeEach(()=>{Object.values(api).forEach(x=>x.mockReset());api.list.mockResolvedValue(page());api.count.mockResolvedValue({unreadCount:1});api.read.mockResolvedValue(undefined);api.all.mockResolvedValue(undefined)})
 it('loads list, count, and exposes loading and server data',async()=>{const{result}=renderHook(()=>useNotifications(),{wrapper});expect(result.current.isLoading).toBe(true);await waitFor(()=>expect(result.current.isLoading).toBe(false));expect(result.current.notifications).toEqual([item]);expect(result.current.unreadCount).toBe(1);expect(api.list.mock.calls[0][0]).toEqual({pageNumber:1,pageSize:20,unreadOnly:false})})
 it('shows errors and retries without fake notifications',async()=>{api.list.mockRejectedValueOnce(new Error('offline'));const{result}=renderHook(()=>useNotifications(),{wrapper});await waitFor(()=>expect(result.current.error?.message).toBe('offline'));expect(result.current.notifications).toEqual([]);act(()=>result.current.reload());await waitFor(()=>expect(result.current.notifications).toHaveLength(1))})
 it('reloads for unread filtering and page navigation',async()=>{const{result}=renderHook(()=>useNotifications(),{wrapper});await waitFor(()=>expect(result.current.isLoading).toBe(false));act(()=>result.current.setUnreadOnly(true));await waitFor(()=>expect(api.list).toHaveBeenLastCalledWith({pageNumber:1,pageSize:20,unreadOnly:true},expect.any(AbortSignal)));act(()=>result.current.setPageNumber(2));await waitFor(()=>expect(api.list).toHaveBeenLastCalledWith({pageNumber:2,pageSize:20,unreadOnly:true},expect.any(AbortSignal)))})
 it('marks one only after success and reloads authoritative state',async()=>{api.list.mockResolvedValueOnce(page()).mockResolvedValue(page([{...item,isRead:true,readAtUtc:'2026-08-06T12:01:00Z'}]));api.count.mockResolvedValueOnce({unreadCount:1}).mockResolvedValue({unreadCount:0});const{result}=renderHook(()=>useNotifications(),{wrapper});await waitFor(()=>expect(result.current.isLoading).toBe(false));await act(()=>result.current.markAsRead('n1'));await waitFor(()=>expect(result.current.notifications[0].isRead).toBe(true));expect(api.read).toHaveBeenCalledWith('n1');expect(result.current.unreadCount).toBe(0)})
 it('failed mark-read and mark-all preserve state',async()=>{api.read.mockRejectedValue(new Error('failed'));api.all.mockRejectedValue(new Error('failed'));const{result}=renderHook(()=>useNotifications(),{wrapper});await waitFor(()=>expect(result.current.isLoading).toBe(false));await expect(result.current.markAsRead('n1')).rejects.toThrow('failed');await expect(result.current.markAllAsRead()).rejects.toThrow('failed');expect(result.current.notifications[0].isRead).toBe(false);expect(result.current.unreadCount).toBe(1)})
 it('marks all then reloads count and items',async()=>{api.list.mockResolvedValueOnce(page()).mockResolvedValue(page([{...item,isRead:true,readAtUtc:'2026-08-06T12:01:00Z'}]));api.count.mockResolvedValueOnce({unreadCount:1}).mockResolvedValue({unreadCount:0});const{result}=renderHook(()=>useNotifications(),{wrapper});await waitFor(()=>expect(result.current.isLoading).toBe(false));await act(()=>result.current.markAllAsRead());await waitFor(()=>expect(result.current.unreadCount).toBe(0));expect(api.all).toHaveBeenCalledOnce();expect(result.current.notifications[0].isRead).toBe(true)})
 it('aborts on unmount and never writes persistent storage',async()=>{const storage=vi.spyOn(Storage.prototype,'setItem');const{result,unmount}=renderHook(()=>useNotifications(),{wrapper});await waitFor(()=>expect(result.current.isLoading).toBe(false));const signal=api.list.mock.calls[0][1] as AbortSignal;unmount();expect(signal.aborted).toBe(true);expect(storage).not.toHaveBeenCalled()})
})
