import {createContext,useCallback,useContext,useEffect,useMemo,useRef,useState,type ReactNode} from 'react'
import * as api from '../api/notifications'
import type {NotificationPage,NotificationResponse} from '../types/notifications'
interface NotificationState{notifications:NotificationResponse[];unreadCount:number;pageNumber:number;pageSize:number;totalCount:number;totalPages:number;hasPreviousPage:boolean;hasNextPage:boolean;unreadOnly:boolean;isLoading:boolean;error:Error|undefined;reload():void;markAsRead(id:string):Promise<void>;markAllAsRead():Promise<void>;setUnreadOnly(value:boolean):void;setPageNumber(value:number):void}
const Context=createContext<NotificationState|null>(null)
const empty:NotificationPage={items:[],pageNumber:1,pageSize:20,totalCount:0,totalPages:0,hasPreviousPage:false,hasNextPage:false}
export function NotificationsProvider({children}:{children:ReactNode}){const[page,setPage]=useState(empty);const[unreadCount,setUnreadCount]=useState(0);const[unreadOnly,setUnread]=useState(false);const[pageNumber,setPageNumberState]=useState(1);const[isLoading,setLoading]=useState(true);const[error,setError]=useState<Error>();const sequence=useRef(0);const active=useRef<AbortController>(undefined);const reload=useCallback(()=>{active.current?.abort();const controller=new AbortController();active.current=controller;const current=++sequence.current;setLoading(true);setError(undefined);Promise.all([api.getNotificationsAsync({pageNumber,pageSize:20,unreadOnly},controller.signal),api.getUnreadNotificationCountAsync(controller.signal)]).then(([next,count])=>{if(current===sequence.current&&!controller.signal.aborted){setPage(next);setUnreadCount(count.unreadCount)}}).catch(reason=>{if(current===sequence.current&&!controller.signal.aborted)setError(reason instanceof Error?reason:new Error('Notifications request failed.'))}).finally(()=>{if(current===sequence.current&&!controller.signal.aborted)setLoading(false)})},[pageNumber,unreadOnly]);useEffect(()=>{
  // The provider owns this external request lifecycle.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  reload();const request=active.current;return()=>request?.abort()
},[reload]);const markAsRead=useCallback(async(id:string)=>{await api.markNotificationReadAsync(id);reload()},[reload]);const markAllAsRead=useCallback(async()=>{await api.markAllNotificationsReadAsync();reload()},[reload]);const setUnreadOnly=useCallback((value:boolean)=>{setPageNumberState(1);setUnread(value)},[]);const setPageNumber=useCallback((value:number)=>setPageNumberState(Math.max(1,value)),[]);const value=useMemo(()=>({notifications:page.items,unreadCount,pageNumber:page.pageNumber,pageSize:page.pageSize,totalCount:page.totalCount,totalPages:page.totalPages,hasPreviousPage:page.hasPreviousPage,hasNextPage:page.hasNextPage,unreadOnly,isLoading,error,reload,markAsRead,markAllAsRead,setUnreadOnly,setPageNumber}),[page,unreadCount,unreadOnly,isLoading,error,reload,markAsRead,markAllAsRead,setUnreadOnly,setPageNumber]);return <Context.Provider value={value}>{children}</Context.Provider>}
// eslint-disable-next-line react-refresh/only-export-components
export function useNotifications(){const value=useContext(Context);if(!value)throw new Error('useNotifications must be used within NotificationsProvider.');return value}
