import {useEffect,useState} from 'react'
import {getTicketActivityAsync} from '../api/activityLogs'
import type {ActivityLogPage} from '../types/audit'
import {EmptyState,LoadingIndicator} from './Feedback'
import {friendlyActivityLabel} from '../utils/activity'

export function ActivityMetadata({metadata}:{metadata:Record<string,string|null>}){const entries=Object.entries(metadata);return entries.length?<dl className="activity-metadata">{entries.map(([key,value])=><div key={key}><dt>{friendly(key)}</dt><dd>{value??'None'}</dd></div>)}</dl>:null}
export function AuditTrail({ticketId}:{ticketId:string}){const[pageNumber,setPageNumber]=useState(1);const[data,setData]=useState<ActivityLogPage>();const[error,setError]=useState(false);const[retry,setRetry]=useState(0);useEffect(()=>{const c=new AbortController();getTicketActivityAsync(ticketId,{pageNumber,pageSize:20},c.signal).then(setData).catch(e=>{if(e.name!=='AbortError')setError(true)});return()=>c.abort()},[ticketId,pageNumber,retry]);function retryLoad(){setData(undefined);setError(false);setRetry(x=>x+1)}function goToPage(value:number){setData(undefined);setError(false);setPageNumber(Math.max(1,value))}return <section><h2>Audit Trail</h2>{error?<div className="error-summary" role="alert"><p>Activity could not be loaded.</p><button type="button" onClick={retryLoad}>Retry</button></div>:data===undefined?<LoadingIndicator/>:<>{data.items.length===0?<EmptyState title="No activity recorded"/>:<ol className="activity-timeline">{data.items.map(x=><li key={x.id}><strong>{friendlyActivityLabel(x.action)}</strong><span>{x.actorDisplayName??'System'} · <time dateTime={x.occurredAtUtc}>{new Date(x.occurredAtUtc).toLocaleString()}</time></span><ActivityMetadata metadata={x.metadata}/></li>)}</ol>}<nav className="pagination" aria-label="Audit trail pages"><button type="button" disabled={!data.hasPreviousPage} onClick={()=>goToPage(data.pageNumber-1)}>Previous</button><span>Page {data.totalPages?data.pageNumber:0} of {data.totalPages}</span><button type="button" disabled={!data.hasNextPage} onClick={()=>goToPage(data.pageNumber+1)}>Next</button></nav></>}</section>}
function friendly(value:string){return value.replace(/[._]/g,' ').replace(/\b\w/g,x=>x.toUpperCase())}
