import {beforeEach,describe,expect,it,vi} from 'vitest'
const signalr=vi.hoisted(()=>{const connection={state:'Disconnected',start:vi.fn(),stop:vi.fn(),on:vi.fn(),off:vi.fn(),onclose:vi.fn(),onreconnecting:vi.fn(),onreconnected:vi.fn()};const builder={withUrl:vi.fn(),withAutomaticReconnect:vi.fn(),configureLogging:vi.fn(),build:vi.fn()};return{connection,builder}})
vi.mock('@microsoft/signalr',()=>({HubConnectionState:{Disconnected:'Disconnected'},LogLevel:{Warning:3},HubConnectionBuilder:class { constructor(){return signalr.builder} }}))
vi.mock('../app/env',()=>({apiBaseUrl:'https://api.example.test'}))
import {createNotificationConnection,isNotificationRealtimeEvent} from './notificationConnection'
describe('notificationConnection',()=>{beforeEach(()=>{Object.values(signalr.connection).forEach(x=>typeof x==='function'&&x.mockReset());Object.values(signalr.builder).forEach(x=>x.mockReset());signalr.builder.withUrl.mockReturnValue(signalr.builder);signalr.builder.withAutomaticReconnect.mockReturnValue(signalr.builder);signalr.builder.configureLogging.mockReturnValue(signalr.builder);signalr.builder.build.mockReturnValue(signalr.connection);signalr.connection.start.mockResolvedValue(undefined);signalr.connection.stop.mockResolvedValue(undefined)})
it('uses the hub path, automatic reconnect, conservative logging, and latest access token',async()=>{let token='one';const manager=createNotificationConnection({getAccessToken:()=>token,onNotificationCreated:vi.fn()});await manager.start();expect(signalr.builder.withUrl).toHaveBeenCalledWith('https://api.example.test/hubs/notifications',expect.any(Object));const options=signalr.builder.withUrl.mock.calls[0][1];expect(options.accessTokenFactory()).toBe('one');token='two';expect(options.accessTokenFactory()).toBe('two');expect(signalr.builder.withAutomaticReconnect).toHaveBeenCalledOnce();expect(signalr.builder.configureLogging).toHaveBeenCalledWith(3);expect(signalr.connection.on).toHaveBeenCalledTimes(1)})
it('starts once and removes handler on clean idempotent stop',async()=>{const manager=createNotificationConnection({getAccessToken:()=>null,onNotificationCreated:vi.fn()});await manager.start();await manager.start();expect(signalr.connection.start).toHaveBeenCalledOnce();await manager.stop();await manager.stop();expect(signalr.connection.off).toHaveBeenCalledWith('NotificationCreated',expect.any(Function));expect(signalr.connection.stop).toHaveBeenCalledOnce()})
it('ignores malformed events and accepts only safe invalidation shape',()=>{expect(isNotificationRealtimeEvent({message:'unsafe'})).toBe(false);expect(isNotificationRealtimeEvent({notificationId:'n',ticketId:null,type:'T',createdAtUtc:'2026-08-08T00:00:00Z'})).toBe(true)})
it('contains connection failures without crashing',async()=>{signalr.connection.start.mockRejectedValue(new Error('offline'));const manager=createNotificationConnection({getAccessToken:()=>'',onNotificationCreated:vi.fn()});await expect(manager.start()).resolves.toBeUndefined()})})
