using System.Net;
using System.Text.Json;
using HelpDesk.Api.Application.Authorization;
using HelpDesk.Api.Application.Common.Exceptions;
using HelpDesk.Api.Application.Notifications;
using HelpDesk.Api.Contracts.Common;
using HelpDesk.Api.Contracts.Notifications;
using Moq;

namespace HelpDesk.Api.Tests;

public sealed class NotificationEndpointIntegrationTests
{
    public static TheoryData<string,string> Routes=>new(){{"GET","/api/notifications"},{"GET","/api/notifications/unread-count"},{"POST",$"/api/notifications/{Guid.NewGuid()}/read"},{"POST","/api/notifications/read-all"}};
    [Theory,MemberData(nameof(Routes))] public async Task AnonymousRoutesReturn401(string method,string route){await using var f=new AuthApiFactory();var r=await f.CreateClient().SendAsync(new HttpRequestMessage(new HttpMethod(method),route));Assert.Equal(HttpStatusCode.Unauthorized,r.StatusCode);}
    [Fact] public async Task AuthenticatedRoutesReturnExpectedStatusesAndJwtSubjectCannotBeOverridden(){await using var f=new AuthApiFactory();var subject=Guid.NewGuid();var attacker=Guid.NewGuid();var client=f.CreateAuthorizedClient(subject,AppRoles.Employee);client.DefaultRequestHeaders.Add("X-User-Id",attacker.ToString());Assert.Equal(HttpStatusCode.OK,(await client.GetAsync($"/api/notifications?userId={attacker}&recipientUserId={attacker}")).StatusCode);Assert.Equal(HttpStatusCode.OK,(await client.GetAsync("/api/notifications/unread-count")).StatusCode);Assert.Equal(HttpStatusCode.NoContent,(await client.PostAsync($"/api/notifications/{AuthApiFactory.CommentId}/read",null)).StatusCode);Assert.Equal(HttpStatusCode.NoContent,(await client.PostAsync("/api/notifications/read-all",null)).StatusCode);f.NotificationService.Verify(x=>x.GetPagedAsync(subject,It.IsAny<NotificationListRequest>(),It.IsAny<CancellationToken>()),Times.Once);f.NotificationService.Verify(x=>x.GetUnreadCountAsync(subject,It.IsAny<CancellationToken>()),Times.Once);f.NotificationService.Verify(x=>x.MarkAsReadAsync(subject,AuthApiFactory.CommentId,It.IsAny<CancellationToken>()),Times.Once);f.NotificationService.Verify(x=>x.MarkAllAsReadAsync(subject,It.IsAny<CancellationToken>()),Times.Once);}
    [Fact] public async Task ListResponseContainsOnlySafeContractFields(){await using var f=new AuthApiFactory();f.NotificationService.Setup(x=>x.GetPagedAsync(It.IsAny<Guid>(),It.IsAny<NotificationListRequest>(),It.IsAny<CancellationToken>())).ReturnsAsync(new PagedResponse<NotificationResponse>{Items=[new(){Id=Guid.NewGuid(),TicketId=Guid.NewGuid(),Type=NotificationTypes.TicketAssigned,Title="Assigned",Message="Safe",CreatedAtUtc=DateTime.UtcNow}],PageNumber=1,PageSize=20,TotalCount=1,TotalPages=1});var r=await f.CreateAuthorizedClient(Guid.NewGuid(),AppRoles.Employee).GetAsync("/api/notifications");var text=await r.Content.ReadAsStringAsync();Assert.Equal(HttpStatusCode.OK,r.StatusCode);var item=JsonDocument.Parse(text).RootElement.GetProperty("items")[0];Assert.Equal(new[]{"id","ticketId","type","title","message","createdAtUtc","readAtUtc","isRead"},item.EnumerateObject().Select(x=>x.Name));Assert.DoesNotContain("recipient",text,StringComparison.OrdinalIgnoreCase);Assert.DoesNotContain("email",text,StringComparison.OrdinalIgnoreCase);Assert.DoesNotContain("password",text,StringComparison.OrdinalIgnoreCase);}
    [Theory] [InlineData("notfound",404,"notification_not_found")] [InlineData("validation",400,"notification_validation_failed")] [InlineData("unexpected",500,"internal_server_error")]
    public async Task ExceptionsMapToSafeProblemDetails(string kind,int status,string code){await using var f=new AuthApiFactory();Exception error=kind switch{"notfound"=>new NotificationNotFoundException(),"validation"=>new NotificationValidationException(),_=>new InvalidOperationException("secret")};f.NotificationService.Setup(x=>x.MarkAsReadAsync(It.IsAny<Guid>(),It.IsAny<Guid>(),It.IsAny<CancellationToken>())).ThrowsAsync(error);var r=await f.CreateAuthorizedClient(Guid.NewGuid(),AppRoles.Employee).PostAsync($"/api/notifications/{Guid.NewGuid()}/read",null);var json=JsonDocument.Parse(await r.Content.ReadAsStringAsync()).RootElement;Assert.Equal(status,(int)r.StatusCode);Assert.Equal(code,json.GetProperty("code").GetString());Assert.False(string.IsNullOrWhiteSpace(json.GetProperty("traceId").GetString()));if(status==500)Assert.DoesNotContain("secret",json.GetRawText());}
    [Fact] public async Task InvalidQueryReturnsSafeValidationProblem(){await using var f=new AuthApiFactory();var r=await f.CreateAuthorizedClient(Guid.NewGuid(),AppRoles.Employee).GetAsync("/api/notifications?pageSize=0");Assert.Equal(HttpStatusCode.BadRequest,r.StatusCode);var text=await r.Content.ReadAsStringAsync();Assert.Contains("validation_failed",text);Assert.Contains("traceId",text);}
}
