using System.Net;using HelpDesk.Api.Application.Ai;using HelpDesk.Api.Application.Common.Exceptions;using HelpDesk.Api.Configuration;using HelpDesk.Api.Infrastructure.Ai;using Microsoft.Extensions.Options;
namespace HelpDesk.Api.Tests;
public sealed class OpenAiTicketProviderTests
{[Fact]public async Task MissingKeyIsUnavailableWithoutNetwork(){var handler=new Handler(_=>throw new InvalidOperationException("network must not run"));var provider=Provider(handler,new AiOptions());await Assert.ThrowsAsync<AiServiceUnavailableException>(()=>provider.AnalyzeAsync(Input()));Assert.Equal(0,handler.Calls);}
[Fact]public async Task MalformedOutputIsSafeProviderFailure(){var handler=new Handler(_=>new HttpResponseMessage(HttpStatusCode.OK){Content=new StringContent("{\"output\":[]}")});await Assert.ThrowsAsync<AiProviderException>(()=>Provider(handler,Settings()).AnalyzeAsync(Input()));Assert.Equal(1,handler.Calls);}
[Fact]public async Task StructuredOutputIsParsedWithoutReturningRawResponse(){var body="""{"output":[{"content":[{"type":"output_text","text":"{\"summary\":\"Safe\",\"recommendedCategoryName\":\"Hardware\",\"recommendedPriorityName\":null,\"troubleshootingSuggestions\":[\"Check power\",\"Restart safely\",\"Verify recovery\"]}"}]}]}""";var handler=new Handler(_=>new HttpResponseMessage(HttpStatusCode.OK){Content=new StringContent(body)});var result=await Provider(handler,Settings()).AnalyzeAsync(Input());Assert.Equal("Safe",result.Summary);Assert.Equal("Hardware",result.RecommendedCategoryName);Assert.Equal(3,result.TroubleshootingSuggestions.Count);}
[Fact]public async Task EmptyTroubleshootingOutputIsRejected(){var body="""{"output":[{"content":[{"type":"output_text","text":"{\"summary\":\"Safe\",\"recommendedCategoryName\":null,\"recommendedPriorityName\":null,\"troubleshootingSuggestions\":[]}"}]}]}""";var handler=new Handler(_=>new HttpResponseMessage(HttpStatusCode.OK){Content=new StringContent(body)});await Assert.ThrowsAsync<AiProviderException>(()=>Provider(handler,Settings()).AnalyzeAsync(Input()));}
private static OpenAiTicketProvider Provider(HttpMessageHandler handler,AiOptions options)=>new(new HttpClient(handler),Options.Create(options));private static AiOptions Settings()=>new(){ApiKey="test-only",Endpoint="https://provider.test/responses"};private static AiTicketInput Input()=>new("Title","Description",["Hardware"],["High"]);
private sealed class Handler(Func<HttpRequestMessage,HttpResponseMessage>response):HttpMessageHandler{public int Calls{get;private set;}protected override Task<HttpResponseMessage>SendAsync(HttpRequestMessage request,CancellationToken cancellationToken){Calls++;return Task.FromResult(response(request));}}}
