using HelpDesk.Api.Contracts.Reports;
using HelpDesk.Api.Application.Authorization;
using HelpDesk.Api.Application.Tickets;
using HelpDesk.Api.Data;
using HelpDesk.Api.Entities;
using HelpDesk.Api.Infrastructure.Reports;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;

namespace HelpDesk.Api.Tests;

public sealed class ReportServiceTests
{
    [Fact]public async Task MetricsBreakdownsTrendAndWorkload_UseRealCurrentData(){await using var f=await Fixture.Create();var r=await f.Service.GetTicketReportAsync(new(),f.Access);Assert.Equal(3,r.Summary.TotalTickets);Assert.Equal(2,r.Summary.OpenTickets);Assert.Equal(1,r.Summary.TerminalTickets);Assert.Equal(1,r.Summary.CancelledTickets);Assert.Equal(2,r.Summary.AssignedTickets);Assert.Equal(1,r.Summary.UnassignedTickets);Assert.Equal(2,r.StatusBreakdown.Single(x=>x.Name=="Open").Count);Assert.Equal(1,r.PriorityBreakdown.Single(x=>x.Name=="Medium").Count);Assert.Equal(2,r.CategoryBreakdown.Single(x=>x.Name=="Hardware").Count);Assert.Equal(2,r.Trend.Sum(x=>x.CreatedCount));Assert.Equal(1,r.Trend.Sum(x=>x.ClosedCount));Assert.Equal(1,r.AgentWorkload.Single(x=>x.UserId==f.AgentId).ActiveTicketCount);Assert.Null(r.Summary.AverageResolutionMinutes);}
    [Fact]public async Task LookupDateAndAgentFilters_AreCombined(){await using var f=await Fixture.Create();var r=await f.Service.GetTicketReportAsync(new(){FromUtc=new DateTime(2026,8,2,0,0,0,DateTimeKind.Utc),ToUtc=new DateTime(2026,8,4,23,59,59,DateTimeKind.Utc),CategoryId=1,PriorityId=1,StatusId=1,AssignedToUserId=f.AgentId},f.Access);Assert.Equal(1,r.Summary.TotalTickets);Assert.Equal(1,r.Summary.AssignedTickets);Assert.Equal(1,r.CategoryBreakdown.Single(x=>x.Id==1).Count);}
    [Fact]public async Task ZeroResult_ReturnsZerosWithoutFabrication(){await using var f=await Fixture.Create();var r=await f.Service.GetTicketReportAsync(new(){FromUtc=new DateTime(2025,1,1,0,0,0,DateTimeKind.Utc),ToUtc=new DateTime(2025,1,2,0,0,0,DateTimeKind.Utc)},f.Access);Assert.Equal(0,r.Summary.TotalTickets);Assert.All(r.StatusBreakdown,x=>Assert.Equal(0,x.Count));Assert.All(r.AgentWorkload,x=>Assert.Equal(0,x.ActiveTicketCount));Assert.All(r.Trend,x=>{Assert.Equal(0,x.CreatedCount);Assert.Equal(0,x.ClosedCount);});}
    [Fact]public async Task AverageResolution_UsesValidResolvedTicketsAndAllFilters(){await using var f=await Fixture.Create();var resolved=Fixture.Ticket("4",1,1,4,new DateTime(2026,8,2,0,0,0,DateTimeKind.Utc),f.AgentId,null);resolved.ResolvedAtUtc=resolved.CreatedAtUtc.AddMinutes(30);var second=Fixture.Ticket("5",2,2,4,new DateTime(2026,8,3,0,0,0,DateTimeKind.Utc),f.AgentId,null);second.ResolvedAtUtc=second.CreatedAtUtc.AddHours(2);var cancelled=Fixture.Ticket("6",1,1,4,new DateTime(2026,8,3,0,0,0,DateTimeKind.Utc),f.AgentId,null);cancelled.ResolvedAtUtc=cancelled.CreatedAtUtc.AddHours(10);cancelled.CancelledAtUtc=cancelled.ResolvedAtUtc;var invalid=Fixture.Ticket("7",1,1,4,new DateTime(2026,8,4,0,0,0,DateTimeKind.Utc),f.AgentId,null);invalid.ResolvedAtUtc=invalid.CreatedAtUtc.AddMinutes(-5);f.Db.Tickets.AddRange(resolved,second,cancelled,invalid);await f.Db.SaveChangesAsync();var all=await f.Service.GetTicketReportAsync(new(),f.Access);Assert.Equal(75,all.Summary.AverageResolutionMinutes);var filtered=await f.Service.GetTicketReportAsync(new(){FromUtc=new DateTime(2026,8,1,0,0,0,DateTimeKind.Utc),ToUtc=new DateTime(2026,8,2,23,59,59,DateTimeKind.Utc),CategoryId=1,PriorityId=1,StatusId=4,AssignedToUserId=f.AgentId},f.Access);Assert.Equal(30,filtered.Summary.AverageResolutionMinutes);}
    [Fact]public async Task AgentProjection_IsSafeAndInvalidLookupIsRejected(){await using var f=await Fixture.Create();var r=await f.Service.GetTicketReportAsync(new(),f.Access);Assert.Equal(["UserId","DisplayName","ActiveTicketCount"],typeof(AgentWorkloadResponse).GetProperties().Select(x=>x.Name));Assert.DoesNotContain("agent@example.test",System.Text.Json.JsonSerializer.Serialize(r));await Assert.ThrowsAsync<HelpDesk.Api.Application.Common.Exceptions.TicketValidationException>(()=>f.Service.GetTicketReportAsync(new(){CategoryId=99},f.Access));}

    private sealed class FixedTime:TimeProvider{public override DateTimeOffset GetUtcNow()=>new(2026,8,5,12,0,0,TimeSpan.Zero);}
    private sealed class Fixture(SqliteConnection connection,ApplicationDbContext db,ReportService service):IAsyncDisposable
    {public Guid AgentId{get;}=Guid.Parse("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa");public ApplicationDbContext Db=>db;public ReportService Service=>service;public TicketAccessContext Access=>new(){UserId=AgentId,Roles=[AppRoles.Admin]};
        public static async Task<Fixture>Create(){var c=new SqliteConnection("Data Source=:memory:");await c.OpenAsync();await TicketSqliteDatabase.InitializeAsync(c);var db=new ApplicationDbContext(new DbContextOptionsBuilder<ApplicationDbContext>().UseSqlite(c).Options);var f=new Fixture(c,db,new ReportService(db,new FixedTime()));var now=new DateTime(2026,8,5,12,0,0,DateTimeKind.Utc);db.Users.Add(new User{Id=f.AgentId,UserName="agent",Email="agent@example.test",DisplayName="Agent Safe",CreatedAtUtc=now,UpdatedAtUtc=now});db.UserRoles.Add(new UserRole{UserId=f.AgentId,RoleId=Guid.Parse("22222222-2222-2222-2222-222222222222"),AssignedAtUtc=now});var first=Ticket("1",1,1,1,new DateTime(2026,8,1,0,0,0,DateTimeKind.Utc),null,null);first.CancelledAtUtc=now;db.Tickets.AddRange(first,Ticket("2",1,1,1,new DateTime(2026,8,3,0,0,0,DateTimeKind.Utc),f.AgentId,null),Ticket("3",2,2,5,new DateTime(2026,7,1,0,0,0,DateTimeKind.Utc),f.AgentId,now));await db.SaveChangesAsync();return f;}
        public static Ticket Ticket(string suffix,short category,short priority,short status,DateTime created,Guid? assigned,DateTime? closed)=>new(){Id=Guid.Parse($"00000000-0000-0000-0000-00000000000{suffix}"),ReferenceNumber="R-"+suffix,Title="T",Description="D",CategoryId=category,PriorityId=priority,StatusId=status,CreatedByUserId=Guid.NewGuid(),AssignedToUserId=assigned,CreatedAtUtc=created,UpdatedAtUtc=created,ClosedAtUtc=closed};
        public async ValueTask DisposeAsync(){await db.DisposeAsync();await connection.DisposeAsync();}}
}
