using HelpDesk.Api.Application.Authorization;
using HelpDesk.Api.Application.Notifications;
using HelpDesk.Api.Data;
using HelpDesk.Api.Entities;
using HelpDesk.Api.Infrastructure.Notifications;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using Moq;

namespace HelpDesk.Api.Tests;

public sealed class TicketNotificationServiceTests
{
    private static readonly Guid Ticket=Guid.Parse("dddddddd-dddd-dddd-dddd-dddddddddddd");
    [Fact] public async Task Assignment_NotifiesNewAssigneeWithStableTypeAndExcludesActor(){await using var f=await Fixture.Create();await f.Service.NotifyAssignmentAsync(Ticket,"TKT-1",f.Assignee,f.Actor);f.Verify(f.Assignee,NotificationTypes.TicketAssigned);f.Mock.Invocations.Clear();await f.Service.NotifyAssignmentAsync(Ticket,"TKT-1",f.Actor,f.Actor);Assert.Empty(f.Mock.Invocations);}
    [Fact] public async Task Status_NotifiesCreatorUnlessCreatorActs(){await using var f=await Fixture.Create();await f.Service.NotifyStatusChangedAsync(Ticket,"TKT-1",f.Creator,f.Actor,"Closed");f.Verify(f.Creator,NotificationTypes.TicketStatusChanged);f.Mock.Invocations.Clear();await f.Service.NotifyStatusChangedAsync(Ticket,"TKT-1",f.Creator,f.Creator,"Closed");Assert.Empty(f.Mock.Invocations);}
    [Fact] public async Task PublicComment_DeduplicatesCreatorAndAssigneeAndExcludesAuthor(){await using var f=await Fixture.Create();await f.Service.NotifyCommentAddedAsync(Ticket,"TKT-1",f.Creator,f.Creator,f.Actor,false);f.Verify(f.Creator,NotificationTypes.TicketCommentAdded);Assert.Single(f.Mock.Invocations);f.Mock.Invocations.Clear();await f.Service.NotifyCommentAddedAsync(Ticket,"TKT-1",f.Creator,f.Assignee,f.Creator,false);f.Verify(f.Assignee,NotificationTypes.TicketCommentAdded);Assert.Single(f.Mock.Invocations);}
    [Fact] public async Task InternalComment_OnlyNotifiesSupportAssigneeAndExcludesAuthor(){await using var f=await Fixture.Create();await f.AddRole(f.Assignee,AppRoles.ItSupportAgent);await f.Service.NotifyCommentAddedAsync(Ticket,"TKT-1",f.Creator,f.Assignee,f.Actor,true);f.Verify(f.Assignee,NotificationTypes.TicketInternalCommentAdded);f.Mock.Invocations.Clear();await f.Service.NotifyCommentAddedAsync(Ticket,"TKT-1",f.Creator,f.Creator,f.Actor,true);Assert.Empty(f.Mock.Invocations);await f.Service.NotifyCommentAddedAsync(Ticket,"TKT-1",f.Creator,f.Assignee,f.Assignee,true);Assert.Empty(f.Mock.Invocations);}
    [Fact] public async Task Cancellation_DeduplicatesRecipientsAndExcludesActor(){await using var f=await Fixture.Create();await f.Service.NotifyTicketCancelledAsync(Ticket,"TKT-1",f.Creator,f.Creator,f.Actor);f.Verify(f.Creator,NotificationTypes.TicketCancelled);Assert.Single(f.Mock.Invocations);f.Mock.Invocations.Clear();await f.Service.NotifyTicketCancelledAsync(Ticket,"TKT-1",f.Creator,f.Assignee,f.Creator);f.Verify(f.Assignee,NotificationTypes.TicketCancelled);Assert.Single(f.Mock.Invocations);}
    [Fact] public async Task Attachment_DeduplicatesRecipientsAndExcludesUploader(){await using var f=await Fixture.Create();await f.Service.NotifyAttachmentAddedAsync(Ticket,"TKT-1",f.Creator,f.Assignee,f.Creator);f.Verify(f.Assignee,NotificationTypes.TicketAttachmentAdded);Assert.Single(f.Mock.Invocations);f.Mock.Invocations.Clear();await f.Service.NotifyAttachmentAddedAsync(Ticket,"TKT-1",f.Creator,f.Creator,f.Actor);f.Verify(f.Creator,NotificationTypes.TicketAttachmentAdded);Assert.Single(f.Mock.Invocations);}
    [Fact] public void MessagesArePlainSafeAndInterfaceHasNoHttpDependencies(){Assert.All(typeof(ITicketNotificationService).GetMethods(),m=>Assert.DoesNotContain(m.GetParameters(),p=>p.ParameterType.Name.Contains("Http")||p.ParameterType.Name.Contains("Claims")));}
    private sealed class Fixture(SqliteConnection connection,ApplicationDbContext db,Mock<INotificationService> mock):IAsyncDisposable
    {public Guid Creator{get;}=Guid.Parse("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa");public Guid Assignee{get;}=Guid.Parse("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb");public Guid Actor{get;}=Guid.Parse("cccccccc-cccc-cccc-cccc-cccccccccccc");public Mock<INotificationService> Mock=>mock;public TicketNotificationService Service{get;}=new(mock.Object,db);public void Verify(Guid recipient,string type)=>mock.Verify(x=>x.CreateAsync(recipient,Ticket,type,It.IsAny<string>(),It.Is<string>(m=>!m.Contains('<')&&!m.Contains('>')),null,It.IsAny<CancellationToken>()),Times.Once);public async Task AddRole(Guid user,string name){var role=await db.Roles.SingleAsync(x=>x.Name==name);db.UserRoles.Add(new UserRole{UserId=user,RoleId=role.Id,AssignedAtUtc=DateTime.UtcNow});await db.SaveChangesAsync();}public static async Task<Fixture>Create(){var c=new SqliteConnection("Data Source=:memory:");await c.OpenAsync();await TicketSqliteDatabase.InitializeAsync(c);var db=new ApplicationDbContext(new DbContextOptionsBuilder<ApplicationDbContext>().UseSqlite(c).Options);return new(c,db,new Mock<INotificationService>());}public async ValueTask DisposeAsync(){await db.DisposeAsync();await connection.DisposeAsync();}}
}
