import { beforeEach, describe, expect, it, vi } from 'vitest'
import { apiRequest, ApiProblemError } from './apiClient'
import { tokenStore } from '../auth/tokenStore'
const json = (value: unknown, status=200) => new Response(JSON.stringify(value), { status, headers:{'content-type':'application/json'} })
describe('apiRequest', () => {
  beforeEach(() => tokenStore.clear())
  it('omits bearer without a token', async () => { vi.stubGlobal('fetch', vi.fn().mockResolvedValue(json({ok:true}))); await apiRequest('/x'); const init=(vi.mocked(fetch).mock.calls[0][1])!; expect(new Headers(init.headers).has('Authorization')).toBe(false) })
  it('adds bearer and forwards signal without putting token in URL', async () => { tokenStore.set({accessToken:'secret-access',refreshToken:'r'}); vi.stubGlobal('fetch',vi.fn().mockResolvedValue(json({}))); const signal=new AbortController().signal; await apiRequest('/x',{signal}); const [url,init]=vi.mocked(fetch).mock.calls[0]; expect(url).toBe('https://api.test/x'); expect(new Headers(init?.headers).get('Authorization')).toBe('Bearer secret-access'); expect(init?.signal).toBe(signal) })
  it('handles 204', async () => { vi.stubGlobal('fetch',vi.fn().mockResolvedValue(new Response(null,{status:204}))); await expect(apiRequest('/x')).resolves.toBeUndefined() })
  it('parses validation ProblemDetails', async () => { vi.stubGlobal('fetch',vi.fn().mockResolvedValue(json({title:'Invalid',code:'validation_failed',errors:{Email:['Required']}},400))); await expect(apiRequest('/x')).rejects.toMatchObject({status:400,code:'validation_failed',validationErrors:{Email:['Required']}} satisfies Partial<ApiProblemError>) })
  it('coordinates simultaneous refresh and retries each request once', async () => { tokenStore.set({accessToken:'old',refreshToken:'rotate'}); let originalCalls=0; const fetchMock=vi.fn(async (input:string|URL|Request) => { const url=String(input); if(url.endsWith('/api/auth/refresh')) return json({accessToken:'new',refreshToken:'new-r'}); originalCalls++; return originalCalls<=2 ? new Response(null,{status:401}) : json({ok:true}) }); vi.stubGlobal('fetch',fetchMock); await Promise.all([apiRequest('/one'),apiRequest('/two')]); expect(fetchMock.mock.calls.filter(call=>String(call[0]).endsWith('/api/auth/refresh'))).toHaveLength(1); expect(fetchMock).toHaveBeenCalledTimes(5) })
  it('clears tokens when refresh fails without recursion', async () => { tokenStore.set({accessToken:'old',refreshToken:'r'}); vi.stubGlobal('fetch',vi.fn().mockResolvedValueOnce(new Response(null,{status:401})).mockResolvedValueOnce(new Response(null,{status:401}))); await expect(apiRequest('/x')).rejects.toBeInstanceOf(ApiProblemError); expect(tokenStore.getAccessToken()).toBeNull(); expect(vi.mocked(fetch)).toHaveBeenCalledTimes(2) })
})
